spring:
  application:
    name: eureka-swagger-server

server:
  port: 8761
logging:
  level:
    com.netflix.eureka: false
    com.netflix.discovery: false


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false