server:
  port: 9093

spring:
  application:
    name: documentation-app

eureka:
  instance:
    appname: documentation-app
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

swagger:
  config:
    refreshrate: 5000